In [1]:
#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("C:\\Users\\ajroy\\OneDrive\\Desktop\\New folder\\instagram_comments_project\\comments.csv")
print(df)


        id                 comment  User  id  Photo id created Timestamp  \
0        1         unde at dolorem         2         1  13-04-2023 08:04   
1        2         quae ea ducimus         3         1  13-04-2023 08:04   
2        3      alias a voluptatum         5         1  13-04-2023 08:04   
3        4    facere suscipit sunt        14         1  13-04-2023 08:04   
4        5  totam eligendi quaerat        17         1  13-04-2023 08:04   
...    ...                     ...       ...       ...               ...   
7483  7484       accusamus vel est        82       257  13-04-2023 08:04   
7484  7485           sit nulla qui        91       257  13-04-2023 08:04   
7485  7486        sed quidem vitae        93       257  13-04-2023 08:04   
7486  7487   dolorem eveniet rerum        95       257  13-04-2023 08:04   
7487  7488  dolores nihil voluptas        96       257  13-04-2023 08:04   

     posted date emoji used  Hashtags used count  
0       April 14        yes         

In [2]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7488 entries, 0 to 7487
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   id                   7488 non-null   int64 
 1   comment              7488 non-null   object
 2   User  id             7488 non-null   int64 
 3   Photo id             7488 non-null   int64 
 4   created Timestamp    7488 non-null   object
 5   posted date          7488 non-null   object
 6   emoji used           7488 non-null   object
 7   Hashtags used count  7488 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 468.1+ KB


In [3]:
df['id'].unique()

array([   1,    2,    3, ..., 7486, 7487, 7488], shape=(7488,))

In [7]:
df['comment'].unique()


array(['unde at dolorem', 'quae ea ducimus', 'alias a voluptatum', ...,
       'sed quidem vitae', 'dolorem eveniet rerum',
       'dolores nihil voluptas'], shape=(7467,), dtype=object)

In [12]:
df.columns = df.columns.str.replace(' ', '_').str.lower()
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7488 entries, 0 to 7487
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   id                   7488 non-null   int64 
 1   comment              7488 non-null   object
 2   user__id             7488 non-null   int64 
 3   photo_id             7488 non-null   int64 
 4   created_timestamp    7488 non-null   object
 5   posted_date          7488 non-null   object
 6   emoji_used           7488 non-null   object
 7   hashtags_used_count  7488 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 468.1+ KB


In [14]:
#checking username column for cleaning
df['user__id'].unique()

array([  2,   3,   5,  14,  17,  21,  24,  31,  36,  41,  52,  54,  55,
        57,  62,  63,  66,  71,  72,  75,  76,  78,  87,  91,  98,  15,
        18,  19,  28,  30,  35,  42,  43,  47,  48,  60,  65,  82,  85,
        95,  27,  37,  38,  44,  50,  67,  70,  79,  97,   6,   8,  11,
        20,  22,  26,  33, 100,  84,  94,  46,  61,  73,  93,  99,   9,
        10,  40,  56,  92,  32,  39,  96,  69,  12,  13,  16,   4])

In [15]:
df['photo_id'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [16]:
df['created_timestamp'].unique()

array(['13-04-2023 08:04'], dtype=object)

In [17]:
df['posted_date'].unique()

array(['April 14'], dtype=object)

In [18]:
df['emoji_used'].unique()

array(['yes', 'no'], dtype=object)

In [19]:
df['hashtags_used_count'].unique()

array([1, 2, 4, 0, 5, 6, 3])